name: Release npm package

on:
  push:
    branches:
      - development
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.TOKEN }}
      - uses: actions/setup-node@v1
        with:
          node-version: "16"

      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          GIT_AUTHOR_NAME: ehabzaki
          GIT_AUTHOR_EMAIL: m.ehabzaki@gmail.com
          GIT_COMMITTER_NAME: ehabzaki
          GIT_COMMITTER_EMAIL: m.ehabzaki@gmail.com
